main: ru.pepej.kitpvp.KitPvPCore
version: '1.0.0'
author: pepej
name: KitPvP
depend:
  - KotlinBukkitAPI
  - TouchscreenHolograms
commands:
  kits:
    description: none
  create:
    description: none
  remove:
    description: none
  apply:
    description: none
  edit:
    description: none
  preview:
    description: none